### ISSUE TITLE
Console error: Uncaught TypeError: paypal.getFundingSources is not a function

### ISSUE THREAD

**Issue by mattallan** [woocommerce/woocommerce-gateway-paypal-express-checkout#739]
### Describe the bug

Customers have started reporting a javascript error after updating to 2.0.0. See first report: https://wordpress.org/support/topic/latest-version-has-js-critical-error/

I have been able to replicate this by activating PayPal Powered by Braintree Gateway which is still using the older `checkout.js` file 😢 

Steps to replicate:
1. Activate PayPal Powered by Braintree gateway and set it up in sandbox mode
   1. _If you don't have PayPal Braintree you should be able to just update [this condition](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/d958f601a32f5a2cdf6319186b8b7205c518a96b/includes/class-wc-gateway-ppec-cart-handler.php#L535) to always fail by adding `false &&`._
2. Enable smart payment buttons on the checkout page
3. Set **Hide payment methods** setting to have 1 or more payment options disabled: https://d.pr/i/xuUmyk
4. Load the checkout page 

You should notice that no PayPal buttons are loaded and the error in console:
![](https://d.pr/i/CgniFx+)
